labd/terraform-provider-commercetools

- commercetools/resource_subscription.go
- commercetools/resource_subscription_test.go
Add validation for the destination property for the subtype given by the `type`field.
> Add validation for destination.

- commercetools/resource_subscription.go
- go.mod
- go.sum
> Add untested support for changing destination

- commercetools/provider.go
- commercetools/resource_channel.go
- docs/resource_channel.md
This doesn't yet support the optional fields address/custom and
geolocation
> Add minimal implementation of the channel resource

- commercetools/resource_type.go
- commercetools/resource_type_test.go
Tried to fix linting error, but apparently conversion has to be done this way to properly convert....
> Fix interface panic during rollout

- commercetools/resource_api_extension.go
- commercetools/resource_api_extension_test.go
We would like to have the ability to set the extension timeouts from our terraform, so I created this PR to add that functionality. First time writing any go so let me know if there's any changes that need to be made!
> Add support for timeoutInMs field in api extension type

- commercetools/resource_subscription.go
- commercetools/resource_subscription_test.go
- docs/resource_subscription.md
Hi there!
While trying out this provider for our own project, we noticed that the Azure Event Grid destination for subscriptions was not yet implemented. So... here it is!
I did not extend on the testing that much, since it was not that extensive for subscriptions to begin with, but let me know if that is something you would require.
Have a good day
> Azure eventgrid support

- commercetools/resource_api_client.go
- commercetools/resource_api_extension.go
- commercetools/resource_channel.go
- commercetools/resource_product_type.go
- commercetools/resource_shipping_method.go
- commercetools/resource_shipping_zone.go
- commercetools/resource_shipping_zone_rate.go
- commercetools/resource_state.go
- commercetools/resource_store.go
- commercetools/resource_subscription.go
- commercetools/resource_tax_category.go
- commercetools/resource_tax_category_rate.go
- commercetools/resource_type.go
- commercetools/utils.go
> Dont retry on CT errors, make create calls more consistent

- commercetools/resource_product_type.go
- commercetools/resource_product_type_test.go
- commercetools/utils.go
* allow modifying also sets of (localized) enums
* allow adding/removing/changing translations for a localized enum
> Allow adding/removing/changing translations for a (set of) localized enum

- commercetools/resource_api_client.go
- commercetools/resource_api_extension.go
- commercetools/resource_api_extension_test.go
- commercetools/resource_cart_discount.go
- commercetools/resource_channel.go
- commercetools/resource_discount_code.go
- commercetools/resource_product_type.go
- commercetools/resource_shipping_method.go
- commercetools/resource_shipping_zone.go
- commercetools/resource_shipping_zone_rate.go
- commercetools/resource_state.go
- commercetools/resource_store.go
- commercetools/resource_subscription.go
- commercetools/resource_tax_category.go
- commercetools/resource_tax_category_rate.go
- commercetools/resource_type.go
- commercetools/resource_type_test.go
- go.mod
- go.sum
This basically adds `context.Background()` as first parameter to all
calls
> Update compatibility with new commercetools go sdk

- CHANGELOG.md
- commercetools/resource_discount_code.go
- commercetools/resource_discount_code_test.go
- commercetools/resource_product_type.go
* Fixed DiscountCode tests invalid JSON error
* Removed breaking `string` cast from ProductType tests
* MINOR: typo fix
> Fix testacc Tests

- commercetools/resource_type.go
- commercetools/resource_type_test.go
* add support for update of set of enums
* add support for update the label of a existing enum
> Add support to update set of enum and also update label of existing enums

- commercetools/resource_project.go
- commercetools/resource_project_test.go
- commercetools/resource_shipping_zone_rate.go
- commercetools/resource_shipping_zone_rate_test.go
- docs-rtd/resource_project.md
- docs-rtd/resource_shipping_method.md
First draft version to add https://github.com/labd/terraform-provider-commercetools/issues/137 functionality to provider.
* TODO: Check ACC tests
Resolves #137
> Add shippingRatePricerTier and shippingRateInputType

- CHANGELOG.md
- commercetools/resource_subscription.go
- commercetools/resource_subscription_test.go
- docs-rtd/resource_subscription.md
> Support EventBridge as subscription option

- commercetools/resource_store.go
Add create supply channel on creation of resource
> Fix issue #210 Add Supply Channel

- commercetools/resource_project.go
The `key` attribute seems to be missing in the state file.
> project_settings: Fix key not being saved

- commercetools/resource_custom_object.go
- commercetools/resource_custom_object_test.go
Fixes https://github.com/labd/terraform-provider-commercetools/issues/139
> custom_object: Use interface{} for decoding custom object values

- commercetools/resource_type.go
- commercetools/resource_type_test.go
- commercetools/utils.go
> type: Fix array index out of bounds error

- commercetools/errors.go
- commercetools/resource_api_client.go
- commercetools/resource_api_extension.go
- commercetools/resource_cart_discount.go
- commercetools/resource_category.go
- commercetools/resource_channel.go
- commercetools/resource_custom_object.go
- commercetools/resource_customer_group.go
- commercetools/resource_discount_code.go
- commercetools/resource_product_type.go
- commercetools/resource_project.go
- commercetools/resource_shipping_method.go
- commercetools/resource_shipping_zone.go
- commercetools/resource_shipping_zone_rate.go
- commercetools/resource_state.go
- commercetools/resource_store.go
- commercetools/resource_subscription.go
- commercetools/resource_tax_category.go
- commercetools/resource_tax_category_rate.go
- commercetools/resource_type.go
- commercetools/utils.go
- go.sum
This PR refactors the handling of errors when calling the commercetools api's and standardizes the output.
> Improve handling of errors returned by commercetools

- commercetools/resource_subscription.go
- commercetools/resource_subscription_test.go
> subscription: Add destination type aliases

- commercetools/resource_api_extension.go
- commercetools/resource_api_extension_test.go
See https://docs.commercetools.com/api/releases/2022-06-08-conditional-api-extensions-in-beta
> Add support for setting a condition on api extension triggers

- .github/workflows/tests.yml
- commercetools/custom_fields.go
- commercetools/resource_category.go
- commercetools/resource_channel.go
- commercetools/resource_channel_test.go
- commercetools/resource_customer_group.go
- commercetools/resource_customer_group_test.go
- commercetools/resource_discount_code.go
- commercetools/resource_discount_code_test.go
- commercetools/resource_shipping_method.go
- commercetools/resource_store.go
- commercetools/resource_store_test.go
- commercetools/utils.go
- docs/resources/category.md
- docs/resources/channel.md
- docs/resources/customer_group.md
- docs/resources/discount_code.md
- docs/resources/shipping_method.md
- docs/resources/store.md
- examples/resources/commercetools_store/resource.tf
This implements the logic for setting custom fields on various resources
TODO:
> Add support for custom fields on resources

- commercetools/resource_product_type.go
> Fix range error while setting product type attributes

- .vscode/settings.json
- commercetools/address.go
- commercetools/resource_channel.go
- commercetools/resource_channel_test.go
- commercetools/utils.go
The fields name, description, geolocation and address were missing
See #60
> Implement all fields of the channel resource

- commercetools/resource_product_type.go
- commercetools/resource_product_type_test.go
- commercetools/utils.go
Same changes as in #274, but for the `product_type` resource.
> Rewrite the resource_product_type update logic

- commercetools/custom_fields.go
- commercetools/resource_category.go
- commercetools/resource_channel.go
- commercetools/resource_customer_group.go
- commercetools/resource_discount_code.go
- commercetools/resource_shipping_method.go
- commercetools/resource_store.go
When setting custom field values directly on resources the value needs
to be encoded based on the type of the field.
Thus we need to fetch the custom type used, map the given value to a
field type and encode it accordingly
Fixes #289
> Fix setting custom field values

- commercetools/resource_shipping_zone_rate.go
Fixes https://github.com/labd/terraform-provider-commercetools/issues/184
> Persist shipping tier rates in state

- commercetools/resource_cart_discount.go
- commercetools/resource_cart_discount_migrate.go
- commercetools/resource_product_discount.go
> Fix Product discount value type validation

- commercetools/custom_fields.go
- commercetools/resource_store_test.go
> Fix custom field value encoders

- commercetools/resource_api_extension.go
- commercetools/resource_subscription.go
> Fix Azure secret handling for extensions and subscriptions

- commercetools/resource_shipping_zone_rate.go
- commercetools/resource_shipping_zone_rate_test.go
- examples/resources/commercetools_shipping_zone_rate/resource.tf
Note that when I ran `make docs`, it introduced a tonne of changes that are not related to my change. I'm happy to add the changes to this PR but wanted to confirm with the maintainers first.
> Add support for price functions on shipping zone rate tiers

- internal/resources/subscription/downgrade_v2.go
- internal/resources/subscription/downgrade_v2_test.go
- internal/resources/subscription/model.go
- internal/resources/subscription/resource.go
- internal/resources/subscription/upgrade_v0_test.go
Optional SingleNestedBlock's are currently not working as supposed in terraform. Instead use a ListNestedBlock with a min size of 1 and max size of 1. In the terraform state this matches how the plugin-sdk-v2 worked, so we can also move back to schema version 1
> Move away from SingleNestedBlock

- README.md
- commercetools/resource_shipping_method.go
- commercetools/resource_shipping_method_test.go
- docs/resources/shipping_method.md
Implements #381, requires https://github.com/labd/commercetools-node-mock/pull/80 and https://github.com/labd/commercetools-node-mock/pull/79 to be released first (WIP)
> feat: add shipping method localized name field

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/support-request.md
> Changed default messages

- commercetools/resource_cart_discount.go
I added support for multiBuyLineItems and multiBuyCustomLineItems. Also I made some small changes for giftLineItem because Supply and Distribution Channel are optional.
> Added multiBuyLineItems and multiBuyCustomLineItems to Cart Discount

- commercetools/resource_store.go
I added support for the [countries](https://docs.commercetools.com/api/projects/stores#storecountry) attribute on the store resource
> Add countries attribute to the store resource

- .changes/unreleased/Fixed-20230816-163609.yaml
- commercetools/resource_api_extension.go
- commercetools/resource_api_extension_test.go
Fixes [309](https://github.com/labd/terraform-provider-commercetools/issues/309)
-  Added correct handling of secrets for azure_authentication in resource_api_extension.go
> Added correct handling of secrets for azure_authentication in resource_api_extension.go

- commercetools/custom_fields.go
- commercetools/resource_cart_discount.go
- commercetools/resource_cart_discount_relative_test.go
- docs/resources/cart_discount.md
- Added custom fields support to the `commercetools_cart_discount` resources.
- Updated documentation.
> Added support for custom fields in Cart Discount

- .changes/unreleased/Fixed-20230816-143923.yaml
- commercetools/custom_fields.go
- commercetools/custom_fields_test.go
Fixes [314](https://github.com/labd/terraform-provider-commercetools/issues/314)
-  fix for customFieldEncodeValue mishandling non-string values
> Added fix for customFieldEncodeValue mishandling non-string values

- commercetools/resource_store.go
- docs/resources/store.md
I changed the type representing the store countries from list to set, so changing the order doesn't result in a change to be applied.
Fixes #422 
- Fixed a bug resulting in a wrong diff on store countries
> fix(store): change countries to set type

- .changes/unreleased/Fixed-20230915-105919.yaml
- internal/acctest/acctest.go
- internal/resources/project/model.go
- internal/resources/project/model_test.go
Fixes #383 
Fixes #430
-  Added fix to update countryTaxRateFallbackEnabled separately
> Added fix to update countryTaxRateFallbackEnabled separately

- .changes/unreleased/Fixed-20230925-095615.yaml
- internal/resources/project/model.go
- internal/resources/project/model_test.go
Fixes #434 
-  prevented issue with bool valueunknown check
> prevented issue with bool valueunknown check

- .changes/unreleased/Fixed-20231115-103727.yaml
- commercetools/resource_discount_code.go
- commercetools/utils.go
- commercetools/utils_test.go
Fixes #449 
- Added additional check for unset values on discount_code resource
> fix: Added additional check for unset values on discount_code resource

- .changes/unreleased/Fixed-20231115-124951.yaml
- internal/resources/project/model.go
- internal/resources/project/model_test.go
Fixes #439 
-  fix: fixed check on project ExternalOAuth setting
> fix: fixed check on project ExternalOAuth setting

- .changes/unreleased/Fixed-20240119-111634.yaml
- commercetools/utils.go
- commercetools/utils_test.go
Fixes #464 
-  Added more support for IETF BCP 47 language tags
> feat(localization): Added more support for IETF BCP 47 language tags

- .changes/unreleased/Fixed-20240126-114842.yaml
- commercetools/custom_fields.go
- docs/guides/custom-fields.md
- docs/guides/state-import.md
- docs/resources/cart_discount.md
- docs/resources/category.md
- docs/resources/channel.md
- docs/resources/customer_group.md
- docs/resources/discount_code.md
- docs/resources/shipping_method.md
- docs/resources/store.md
- templates/guides/custom-fields.md.tmpl
- templates/guides/state-import.md.tmpl
Fixes #321 
Fixes #353 
Fixes #460 
-  Updated various documentation elements
> feat(documentation): Added additional documentation

- .changes/unreleased/Added-20240119-152201.yaml
- docs/resources/subscription.md
- internal/resources/subscription/downgrade_v2.go
- internal/resources/subscription/downgrade_v2_test.go
- internal/resources/subscription/model.go
- internal/resources/subscription/model_test.go
- internal/resources/subscription/resource.go
- internal/resources/subscription/upgrade_v0.go
- internal/resources/subscription/upgrade_v0_test.go
- internal/resources/subscription/utils.go
Fixes #373 #468 
-  Added support for confluence cloud subscription
> feat(subscription): Added support for confluence cloud

- .changes/unreleased/Fixed-20240903-091918.yaml
- commercetools/resource_shipping_zone_rate.go
- commercetools/resource_shipping_zone_rate_test.go
Fixes #518 
Fixes #519 
-  Fix nil pointer exception
> fix: fixed nil pointer exception after sdk update

- .changes/unreleased/Added-20241009-195232.yaml
- commercetools/resource_api_extension.go
Fixes https://github.com/labd/terraform-provider-commercetools/issues/526
-  `resource_api_extension` add support for triggers on `shopping-list`
> feat: add support for shopping-list triggers on resource_api_extension

- .changes/unreleased/Fixed-20241204-103555.yaml
- commercetools/resource_shipping_method.go
> fix: made shipping_method active field default to true

- .changes/unreleased/Fixed-20241220-101846.yaml
- commercetools/provider.go
- docs/index.md
- docs/resources/project_settings.md
- docs/resources/shipping_method.md
- internal/provider/provider.go
- internal/resources/project/resource.go
> fix: fixed broken links

- .changes/unreleased/Fixed-20250214-100041.yaml
- commercetools/resource_tax_category.go
- commercetools/resource_tax_category_rate.go
- commercetools/resource_tax_category_rate_test.go
- docs/resources/tax_category.md
- docs/resources/tax_category_rate.md
- examples/resources/commercetools_tax_category_rate/resource.tf
Fixes #565
- Adds tax category rate key to resources
> feat: added tax category rate key

- .changes/unreleased/Fixed-20250403-085258.yaml
- internal/resources/business_unit_company/model.go
- internal/resources/business_unit_company/model_test.go
- internal/resources/business_unit_division/model.go
- internal/resources/business_unit_division/model_test.go
> fix: empty slice for business units without stores

- .changes/unreleased/Fixed-20250509-154616.yaml
- commercetools/resource_product_type.go
- commercetools/resource_product_type_test.go
Requires https://github.com/labd/commercetools-node-mock/pull/296 to be merged
Fixes #585
-
> fix: added chunking options for product_type resource update
