docs/examples.md

As documented [here](https://docs.commercetools.com/http-api-projects-subscriptions.html#aws-sqs-destination), the SQS queue must be created with the default (maximum) message size. Otherwise, the commercetools platform will not be able to deliver larger messages.
PS: I keep wondering why we've seen quite a few people create queues with this low max message size. Now I know why 😉

Remove max_message_size from SQS example

---

commercetools/resource_project.go
commercetools/resource_project_test.go
docs/resource_project.md

The original PR for this only added the changes to the terraform schema but didn't actually add any logic. This now adds in the logic so that the commercetools project is updated when external_oauth is added.
I also added a couple more tests to the project in order to ensure updating works correctly a second time and that external_oauth can be removed correctly as that required a little bit of extra logic so was worth testing.

fix: add logic for adding and removing external_oauth to/from commercetools

---

Dockerfile

For the provider to run in the container it needs libc6-compat installed.

Fixing missing libc6-compat in docker image

---

commercetools/resource_state.go
commercetools/resource_state_test.go
docs/resource_state.md

State in CommerceTools isn't particularly useful for us unless we can also provide transitions between states (to better enable CS to make changes in the Merchant Center).
This PR adds the transition attribute into state.

Add State Transitions Attribute

---

docs/resource_product_type.md

I bumped into a Terraform error where the "=" was missing. I saw this was because this missing in the documentation as well. Hereby added.

added missing '=' for input_tip

---

.azure-pipelines/jobs/test-ubuntu.yml
Makefile
commercetools/provider.go
commercetools/provider_test.go
docs/index.md
go.sum

commercetools now officially supports regions and cloud providers in the hostnames.
https://docs.commercetools.com/http-api.html#regions
~~Therefore, we should prefer to use `region` and `cloud_provider` fields in the TF provider and let the provider construct the correct hostname.~~ Also, there should not be any default values, as the user should explicitly provide them.
~~The fields `token_url` and `api_url` have been marked as `Removed` in the TF provider schema. However, the `CTP_API_URL` and `CTP_AUTH_URL` environment variables can still be used, for example for the test environment.~~
Update: this PR now changes the following:
- all the fields must be required
- there should not be any default values

refactor(provider): to make fields required and remove default values

---

docs/resource_type.md

- The custom type **field-types** for `sets` wasn't correctly documented. These changes fix that
- Markdown linting rule fixes according to https://github.com/DavidAnson/markdownlint

Markdown Linting and Custom Type Documentation Fixes

---

commercetools/provider.go
commercetools/resource_cart_discount.go
commercetools/resource_cart_discount_test.go
commercetools/resource_discount_code.go
commercetools/resource_discount_code_test.go
commercetools/utils.go
docs/resource_cart_discount.md
docs/resource_discount_code.md
go.mod
go.sum

- Added supporting of new commercetools entity CartDiscount
- MultiBuyLineItems Target MultiBuyCustomLineItems Target (https://docs.commercetools.com/http-api-projects-cartDiscounts#multibuylineitems-target) was skipped because in commercetools it is beta feature
- Custom fields skipped 
- Custom fields skipped 
In future it is possible to extend this entities with missing fields
Notes:
- local testing was successfull (entities update/createation succcessful)

feat: added cart discount and discount code entities

---

commercetools/resource_api_extension.go
commercetools/resource_api_extension_test.go

Fixes #129 
**Cause:** 
Occurrence of both `triggers` as well as `trigger` was causing provider to miss updates to the block. 
**Solution:**
As we allow a slice of actions and will soon allow a slice of triggers for different resourceTypeIDs ( https://github.com/labd/terraform-provider-commercetools/pull/143 ), we should stick to `triggers`. Also added tests to verify.

Bugfix: Adding an action to a `commercetools_api_extension` has no effect

---

CHANGELOG.md
commercetools/resource_api_extension.go
docs-rtd/resource_api_extension.md

Closes https://github.com/labd/terraform-provider-commercetools/issues/154 
The above issue showed that the api_extension resource documentation could do with some more examples.
This PR also removes a type that is not used and invalid

Update documentation for API ext, remove invalid type for api_ext types

---

commercetools/resource_api_extension_test.go
commercetools/resource_cart_discount_test.go
commercetools/resource_custom_object_test.go
commercetools/resource_customer_group_test.go
commercetools/resource_discount_code_test.go
commercetools/resource_product_type_test.go
commercetools/resource_project_test.go
commercetools/resource_shipping_method_test.go
commercetools/resource_shipping_zone_rate_test.go
commercetools/resource_shipping_zone_test.go
commercetools/resource_state_test.go
commercetools/resource_store_test.go
commercetools/resource_subscription_test.go
commercetools/resource_tax_category_rate_test.go
commercetools/resource_tax_category_test.go
commercetools/resource_type_test.go

Add checkDestroy functions to acceptance tests to raise errors in case of dangling resources with specific IDs. This should reduce the occasional erratic and inconsistent responses the acceptance tests can return, both for the mock server as well as an actual commercetool environment.
Closes: https://github.com/labd/terraform-provider-commercetools/issues/153 . For more info see the issue
Pre Merge Checklist:

Add destroy checks to acceptance tests

---

commercetools/resource_api_client.go

When creating/updating `commercetools_api_client`, the secret get leaked in the change log:
```
-/+ resource "commercetools_api_client" "my-api-client" {
~ id     = "0P8tEhJsQ83kqio3MRSzAMI" -> (known after apply)
~ name   = "my-api-client" -> "my-api-client" # forces replacement
~ secret = "fptJxOZPHft2_UoSfXqTUjWTs2VXOoxK" -> (known after apply)
}
```

fix(commercetools_api_client): mark secret field as sensitive

---

commercetools/resource_subscription.go

Similar to https://github.com/labd/terraform-provider-commercetools/pull/178 and to prevent secrets from being leaked into the logs, we need to mark `access_key` and `connection_string` fields as sensitive for the `commercetools_subscription` resource.

fix(commercetools_subscription): set access_key and connection_string fields as sensitive

---

commercetools/resource_category.go

`key` is optional but it is still being sent as an empty string when not set. This causes the CT API to respond with an error because of the empty key. This change prevents the `key` from being included in the create request when not set.

category: Fix empty key being sent during creation

---

commercetools/resource_category.go

Fixes #205 
Assets are created when you create a `commercetools_category` resource for the first time.
Resource:
```tf
resource "commercetools_category" "my-category" {
name = {
en = "Some category"
}
slug = {
en = "some_category"
}
assets {
key = "some_key"
name = {
en = "Image name"
}
description = {
en = "Image description"
}
sources {
uri = "https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Flag_of_the_Netherlands.svg/800px-Flag_of_the_Netherlands.svg.png"
key = "image"
}
}
}
```
Apply this and check with the computed ID:
```sh
curl \
-vvv \
-X GET \
-H "Accept: application/json; charset=utf-8" \
-H "Authorization: Bearer $1" \
"https://api.europe-west1.gcp.commercetools.com/$2/categories/$3"
```
```json
{
"id": "xyz",
"version": 1,
"lastMessageSequenceNumber": 1,
"createdAt": …
```

category: Fix new assets not being added

---

commercetools/resource_project.go

Relates to #209   #128
Since all of its attributes are optional you can create an empty `commercetools_project_settings`.
```hcl
resource "commercetools_project_settings" "t2" {
}
```
When you apply this for the first time, you'll also retrieve some hidden attributes which are set by default on CT.  A newly created [Project](https://docs.commercetools.com/api/projects/project) resource looks like this on the CT API:
```sh
curl \
-X GET \
-H "Accept: application/json; charset=utf-8" \
-H "Authorization: Bearer TOKEN" \
"https://api.europe-west1.gcp.commercetools.com/PROJECT"
```
Project:
```json
{
"key": "KEY",
"name": "NAME",
"countries": [
"DE",
"US"
],
"currencies": [
"EUR",
"USD"
],
"languages": [
"de-DE",
"en-US"
],
"createdAt": "2022-03-25T11:21:17.933Z",
"trialUntil": "2022-05", …
```

project_settings: Fix CT defaults not being computed

---

commercetools/resource_cart_discount.go

`validFrom` and `validUntil` attributes should be set to an RFC3339 formatted date string according to the [docs](https://docs.commercetools.com/api/types#datetime).
Given date example is `2022-10-02T15:04:05.000Z` But dates without trailing zeroes are also valid (`2022-10-02T15:04:05Z`).
The problem is Go removes trailing zeroes while parsing them so both dates are same, with zeroes or not. In our case the exact string is saved to the state. So the comparison always yields false if you used trailing zeroes.
As a remedy, I included a diff check which simply decodes the old and new dates with the existing unmarshal function and compares their Unix seconds to make sure they are not same.

cart_discount: Prevent dates with trailing zeroes from triggering updates

---

commercetools/resource_category.go
commercetools/resource_category_test.go

Allow setting `external_id`
* https://docs.commercetools.com/api/projects/categories#categorydraft

category: Add support for external_id attribute

---

commercetools/resource_api_extension.go
commercetools/resource_api_extension_test.go

Fixes the following error thrown by CT when `timeout_in_ms` value is not set.
```
Error: 'timeoutInMs' must be >0.
```

api_extension: Prevent nil from being set as timeoutInMs value

---

commercetools/resource_project.go

This appears to be incorrectly reading the label value from another setting which doesn't exist.

project_settings: Fix cart classification value labels not being set

---

commercetools/resource_project.go
commercetools/resource_project_test.go
commercetools/utils.go

This change adds support for automatically handling mixed-case languages, currencies & countries
These attributes has to be set in a specific format, otherwise we receive a 400 error from CT. We can use [DiffSupressFunc](https://www.terraform.io/plugin/sdkv2/schemas/schema-behaviors#diffsuppressfunc) to  automatically handle mixed-case codes as long as the format is correct. I added a case-insensitive string equality check on `currencies`, `languages` and `countries` attributes. This prevents mixed-case codes (such as `nL-Nl` language tag) from triggering an update. So users can use mixed-case letters, but during the apply these are converted into the stricter case-sensitive format.

project_settings: Allow setting case-insensitive language, currency and language codes

---

commercetools/resource_project.go

If I'm not mistaken, according to the docs there are two ways to set the `CountryTaxRateFallbackEnabled` value:
- In the `CartsConfiguration`: https://docs.commercetools.com/api/projects/project#ctp:api:type:CartsConfiguration
- or as a separate action: https://docs.commercetools.com/api/projects/project#change-countrytaxratefallbackenabled
It's not clear to me why this is the case, but there is a note under `ChangeCountryTaxRateFallbackEnabled` documentation which says some earlier projects may not have this option.
In my project `CartsConfiguration` doesn't seem to apply the change, I need to send `ChangeCountryTaxRateFallbackEnabled` instead.
Always include `ProjectChangeCountryTaxRateFallbackEnabledAction` along with `ProjectChangeCartsConfigurationAction`. This makes sure both the …

project_settings: Fix country_tax_rate_fallback_enabled not being set

---

commercetools/resource_api_extension.go
commercetools/resource_cart_discount.go
commercetools/resource_customer_group.go
commercetools/resource_product_type.go
commercetools/resource_shipping_method.go
commercetools/resource_shipping_zone.go
commercetools/resource_tax_category.go

Previously this was fixed only for the category resource. (#215)
>`key` is optional but it is still being sent as an empty string when not set. This causes the CT API to respond with an error because of the empty key. This change prevents the `key` from being included in the create request when not set.
This PR fixes the issue for all other affected resource types.
* `cart_discount`
* `customer_group`
* `product_type`
* `shipping_method`
* `shipping_zone`
* `tax_category`

Fix empty keys being set during resource creation

---

commercetools/resource_project.go

I think this change may create a lot of confusion so I decided to revert it.
It sounded like a good idea at first since there can be only one type of `project_settings` resource with some required defaults, but this is not how Terraform users usually work with resources such as this one.
To my knowledge there is no distinction between singleton resources and others. In the ideal workflow you want to manually run `terraform import` to fill in the resource details and you expect to see changes on your plan if an optional attribute is not specified in the config, whether it is singleton or not.
This PR reverts #212 only. But on top of it I'd suggest making these default attributes required, since deleting them (or not specifying them without `Computed: true`) will have no effect and raises …

project_settings: Revert computed optionals change

---

commercetools/resource_type.go

Fixes #234 
If the ordering of fields has not changed while updating a type resource, the CT returns `400 'fieldDefinitions' has not changed` error. Because of this, we simply can't add a new field.
Make sure the old field names and the new ones have the same length while making deep equality check. Newly added fields should never add `changeFieldOrdering` action (which is the cause of the error) unless they are specified at the top.

type: Do not set field ordering when new fields are added at the bottom

---

commercetools/resource_cart_discount.go
commercetools/resource_discount_code.go
commercetools/utils.go
commercetools/utils_test.go

- If two dates are same as a string, suppress the change.
- Retain if one of them could not be parsed.
- Finally, compare the Unix seconds.
To test it, I simply added trailing zeroes to `valid_from` and `valid_to` attributes in the cart_discount test update config.

cart_discount: Fix valid dates check

---

commercetools/marshalling.go
commercetools/resource_api_extension.go
commercetools/resource_api_extension_test.go
commercetools/resource_cart_discount.go
commercetools/resource_category.go
commercetools/resource_channel.go
commercetools/resource_custom_object.go
commercetools/resource_discount_code.go
commercetools/resource_product_type.go
commercetools/resource_project.go
commercetools/resource_shipping_method.go
commercetools/resource_shipping_zone.go
commercetools/resource_shipping_zone_rate.go
commercetools/resource_shipping_zone_test.go
commercetools/resource_state.go
commercetools/resource_store.go
commercetools/resource_subscription.go
commercetools/resource_type.go
commercetools/utils.go

We switched to marshall/unmarshall earlier but it's better to keep the
terraform convention of using flatten and expand.
Flatten is the process of converting native Go values to Terraform state
and Expand is from Terraform state to native Go values.

Use the flatten & expand naming convention

---

commercetools/resource_subscription.go
commercetools/resource_subscription_test.go

Closes #245 #247 
(This PR is forked from pr #252 which adds the same feature for `destination` field types.)

subscription: Add format identifier aliases

---

commercetools/resource_shipping_zone.go

Closes #259 
Fixes an issue where Terraform doesn't preserve sorting order while diffing for changes and the provider keeps applying the same change on the list type.
Since location IDs are unique, and a combination of both keys (country, state) we can make this a set instead to ignore ordering changes.

shipping_zone: Use TypeSet for defining locations to ignore ordering changes

---

commercetools/errors.go

Turns out the error type in the example given with product types is actually platform.GenericRequestError.

fix(404): expand 404 cases

---

commercetools/resource_type.go
commercetools/resource_type_test.go
commercetools/utils.go
go.mod
go.sum

Compare resources based on the expanded types (native go structs)
instead of the raw state. This makes the code more readable.
Furthermore this should fixes some issues regarding order changes

Rewrite the resource_type update logic

---

commercetools/resource_product_type.go
commercetools/resource_product_type_test.go
commercetools/resource_type.go
commercetools/resource_type_test.go

This change upgrades `product_type` and `type` resource schemas to use the list syntax (instead of map) for defining attribute/field value types which seems to be only applicable to enum and set types.
- `type.field.type.value` 
- `product_type.attribute.type.value` 
`attribute` and `field` type attributes are identical, `value` of an attribute is only settable when its `type` is set to `enum` or  `set`, likewise `value` of a field type is only settable when its `type` is set to `Enum` or `Set`.
(Note that, this is already how the `localized_value` works in both resource types.)
Closes #278

Use list for defining attribute and field enum values

---

docs/resources/cart_discount.md

Small fix for the documentation of cart discount. Target should be a block instead of a map.

fix(docs): cart discount target is a block instead of a map

---

commercetools/resource_cart_discount.go
commercetools/resource_category.go
commercetools/resource_customer_group.go
commercetools/resource_discount_code.go
commercetools/resource_product_discount.go
commercetools/resource_shipping_method.go
commercetools/resource_store.go
commercetools/resource_tax_category.go

For some resource the version from the state was used and for other not.
Make this consistent and use the state version where possible.
There are two exceptions, the tax and shipping_method resources. Reason
is that they both have 'fake' child resources
(tax_rate, shipping_method_rate) which modifies the version of the parent

Use the resource version from the terraform state

---

commercetools/resource_project.go
commercetools/resource_project_test.go

Commercetools' [MessagesConfiguration](https://docs.commercetools.com/api/projects/project#messagesconfiguration) allows to set `deleteDaysAfterCreation` to configure the message retention time. The supported values are between 1 and 90 (inclusive).
`make build` and `make test` are running fine locally, but this is my first time writing golang. If the implementation is completely flawed, I can also convert this into an issue.

Add Support for `deleteDaysAfterCreation` in Messages Configuration

---

commercetools/resource_api_extension.go

Resolving issue https://github.com/labd/terraform-provider-commercetools/issues/323
Extensions using "business-units" as trigger can now be applied with terraform

added business-unit

---

internal/resources/project/model.go
internal/resources/project/model_test.go

* fix continues project settings updates as the `ShippingRateCartClassificationValue` is by default nil if you are using fixed shipping rates and the plan is using an empty slice
* Fixed https://github.com/labd/terraform-provider-commercetools/issues/334

Fix continues project settings updates

---

internal/resources/subscription/model.go

Currently any attempt to create a GooglePubSub Subscription fails with the following error message:
```
A test message could not be delivered to this destination: GoogleCloudPubSub topic '' in project '****xxxx'. Please make sure your destination is correctly configured.
```
This is likely due a improper reference to TopicARN rather than Topic, which is used by GCP
This update should resolve this issue

Updating GoogleCloudPubSub to Reference Topic

---

internal/resources/subscription/resource.go

This is only needed when the type is SQS or SNS

Don't require `access_key` if `access_secret` is specified

---

internal/resources/subscription/resource.go

This pull requests removes the validator for access key on subscription resource. Access_secret is only used when cloud platform is AWS

Remove validator for access key

---

commercetools/utils_test.go
go.mod
go.sum
internal/acctest/client.go
internal/resources/state/resource.go
internal/resources/state_transition/resource.go
internal/resources/subscription/resource.go

When a resource was defined in the state but no longer available in commercetools we now remove the value from the state.
Fixes #345

Don't error when a resource is no longer found (drift)

---

internal/resources/subscription/model.go

fix: #362 set URI for destination of EventGrid

---

CHANGELOG.md
docs/resources/type.md

When I was working through the documentation I noticed the example `enum` fields were using a `value` key instead of `label`.

Couple of document updates

---

commercetools/resource_api_extension.go
commercetools/resource_api_extension_test.go

Implement new feature - add new type `GoogleCloudFunction`:
- https://github.com/labd/terraform-provider-commercetools/issues/348
- which is also in SDK: https://github.com/labd/commercetools-go-sdk/blob/2a3c3778415c7794f4ea84a449759da4406f450d/platform/types_extension.go#L88-L93
which was announced in 2023-02-17
- https://docs.commercetools.com/api/releases/2023-02-17-introducing-google-cloud-function-destination-for-api-extensions

add GoogleCloudFunction type to resource_api_extension

---

.changes/unreleased/Fixed-20230816-100220.yaml
commercetools/resource_category.go
commercetools/resource_category_test.go

Fixes [357](https://github.com/labd/terraform-provider-commercetools/issues/357)
- Fixes ForceNew on `commercetools_category` resource

Removed ForceNew from name and key attributes in resource_category

---

commercetools/resource_category.go
commercetools/resource_category_test.go

First needs merging of https://github.com/labd/commercetools-node-mock/pull/99 for the tests to succeed
Fixes [273](https://github.com/labd/terraform-provider-commercetools/issues/273)
- Fixes handling of category assets

Added brute force handling of category assets

---

.changes/unreleased/Fixed-20230829-093530.yaml
commercetools/resource_category_test.go
internal/utils/errors.go
internal/utils/errors_test.go

Bug introduced because of a change in error generation by the SDK (https://github.com/labd/commercetools-go-sdk/commit/2a3c3778415c7794f4ea84a449759da4406f450d)
Fixes #384 
-  Added correct check for resource not found case

Fixed issue with NotFound error not checked correctly

---

.changes/unreleased/Fixed-20231115-113250.yaml
internal/resources/subscription/model.go
internal/resources/subscription/model_test.go

Fixes #440
-  ensure an empty slice is set if subscription messages or changes are removed

fix: ensure an empty slice is set if subscription messages or changes are removed

---

.changes/unreleased/Fixed-20240209-134722.yaml
go.mod
internal/resources/associate_role/resource.go
internal/resources/attribute_group/resource.go
internal/resources/product_selection/resource.go
internal/resources/state/resource.go
internal/resources/state_transition/resource.go
internal/resources/subscription/resource.go

This updates the check if an errors is due to a resource not being found for all new resources (`subscription`, `state`, `state_transitions`, `product_selection`, `attribute_group` and `associate_role`).

Properly handle resource not found errors

---

.changes/unreleased/Changed-20241127-143527.yaml
commercetools/resource_api_client.go
docs/resources/api_client.md

The [API Clients](https://docs.commercetools.com/api/projects/api-clients) allow to override the default token validity but this is only possible during the creation of the api client.
While the access_token's are valid for 48 hours, the lifetime of refresh_tokens is 200 days, which is pretty high. I would like to be able to set custom validity values for the api clients. Especially because there is no way to update existing clients, so after creation hooks wont work here.
Extends `resource_api_client` to read and write the fields `accessTokenValiditySeconds` and `refreshTokenValiditySeconds`.
---
Please double check if these changes are good to go. It seems there is not much that needs to be changed but i am unfamiliar with Go and working with TF providers.

Proposal: Allow to adjust token validity for Api Clients via Terraform

---

.changes/unreleased/Fixed-20241217-190228.yaml
internal/resources/associate_role/resource.go

This PR adds a sorting of the permission-list, which we receive from the commercetools-API. The sorting was added within the function Create, Update and Read of the resource associate-role. The sorting of the permissions, which we get from commercetools, is not predictable so that terraform gets confused (See description of issue #505). After sorting the permissions, so that they are in the same order as in the plan, the create, read and update works fine.
Fixes #505
- Fixed a bug, which prevents the proper creation, updating and reading of permissions from associate-roles

Add a proper sorting of associate-role's permissions

---

.changes/unreleased/Fixed-20250221-160803.yaml
commercetools/resource_type.go
commercetools/resource_type_test.go

Fixes #569
-  Throw error when deleting an enum type. This still allows for renaming enum types, it only checks if the total number of new values is smaller than old values

fix: added check that no enum types are deleted

---

.changes/unreleased/Fixed-20250926-150825.yaml
internal/resources/project/model.go
internal/resources/project/model_test.go

This pull request removes an unnecessary check for the default carts configuration in the `Project` model, simplifying both the implementation and its tests. Now, the carts configuration is always included without checking if it matches default values.
Codebase simplification:
* Removed the `IsDefaultCartsConfiguration` function and all related logic from `internal/resources/project/model.go`, so the carts configuration is always set without checking for default values. [[1]](diffhunk://#diff-ea98c1ce792b12a8f06a166483106a667595c3a1dc6ae3467b33fb6fb04cf61bL50-L56) [[2]](diffhunk://#diff-ea98c1ce792b12a8f06a166483106a667595c3a1dc6ae3467b33fb6fb04cf61bL91) [[3]](diffhunk://#diff-ea98c1ce792b12a8f06a166483106a667595c3a1dc6ae3467b33fb6fb04cf61bL100)
* Deleted all associated unit tests for …

feat: removed unnecessary check on default carts type
